default_template = "/_templates/index.html"

[catalogs]
default_card_template = "/_templates/link.html"

[[catalogs.entries]]
title = "Статьи"
path = "/articles"
directory = "/"
card_template = "/_templates/article-card.html"

[[catalogs.entries]]
title = "Посты"
path = "/posts"
directory = "/posts"


[meta]
title_template = "%title% | Your site"
description_template = "%description%"
keywords_template = "%keywords%, your keywords"
fallback_title = "Fallback title"
fallback_description = "Fallback description"
fallback_keywords = "Fallback keywords"


[lazyness]
images = true
first_image = false
