default_template = "/_templates/index.html"
hotreload = false
debug = false

[catalogs]
default_catalog_template = "/_templates/index.html"
default_card_template = "/_templates/link.html"

[[catalogs.entries]]
title = "Статьи"
path = "/articles"
directory = "/"
card_template = "/_templates/article-card.html"

[[catalogs.entries]]
title = "Посты"
path = "/posts"
directory = "/posts"


[meta]

[[meta.tags]]
key = "title"
template = "%s | Sitename"
fallback = "No title"
tag = "title"

[[meta.tags]]
key = "keywords"
template = "%s, electrostatic"
fallback = "No keywords"
tag = "meta"

[[meta.tags]]
key = "description"
template = "%s"
fallback = "No description"
tag = "meta"

[[meta.tags]]
key = "date"
template = "%s"
fallback = ""
tag = "meta"

[lazyness]
images = true
first_image = false
